<?php
return [
   'judul-info' => 'JARIAH ULUNG CHARITY PROJECT :',
   'judul-info-2' => 'DIGITIZATION, TRANSLATION & COMMENTARY OF THE BOOK OF MISHKAT AL-MASABIH',

    // === languange desk === //
    'h1-deks' => 'INTRODUCTION',
    'p-desk-1' => 'The book Mishkat al-Masabih was compiled by Waliud-din Abdullah Muhammad bin ‘Abdullah al Khatib al-Umari at-Tibrizi (d. 741 AH) or better known as Khatib al-Tibrizi. This book improves the shortcomings found in the book Masabih al-Sunnah by Imam Al-Baghawi (d. 516 AH).',
    'p-desk-2' => "This book can be <span class='poppins-bold text-[#E67E4D]'>compared to a summary of Sahih Bukhari </span> where the content is almost the same as the authentic one. What distinguishes the two is the number of hadiths that are more in Sahih Bukhari and also the status of the hadith. Readers of this book will be able to appreciate the demands of a Muslim's life based on the sunnah of the Prophet Muhammad (PBUH). Apart from that, the discussion is divided into several clauses according to the orientation of the content of the hadith, making it easier for the reader to make reference to any hadith they want.",
    'p-deks-3' => "The authors, namely Imam Baghawi and Imam al-Tibrizi, did not include only hadiths that were considered authentic in their books. This resulted in a mixture of hadiths that were weak and could not be used as evidence with authentic hadiths.",
    'p-deks-4' => 'Since to date there is still no digital application that focuses on the reference of the book Mishkat al-Masabih and the suitability of this book to be used as a virtual reference source, Elzar Shariah Solution Sdn Bhd as the project manager wants to develop a smart application or apps called <span class="poppins-bold text-[#E67E4D]">Masabih</span>  to make it easier for the community and Muslims in Malaysia, especially to obtain access and information on <span class="poppins-bold text-[#E67E4D]"> hadith and hadith fiqh </span> as well as answers to questions in life based on the relevant hadith directly and quickly.',
    'p-deks-5' => 'It is hoped that the Masabih Web and Mobile Application can enlighten the Muslim community about the importance of the hadith and sunnah of the Prophet Muhammad SAW, as well as being a guide and reference for the Muslim community as a whole. This application will be developed all at once and donated to the general public, it will be accessible and used for <span class="poppins-bold text-[#E67E4D]">FREE</span>  by the general public.',
];