<?php
return [
   'judul-info' => 'PROJEK AMAL JARIAH ULUNG :',
   'judul-info-2' => 'PENDIGITALAN, TERJEMAHAN & SYARAH KITAB MISHKAT AL-MASABIH',

    // === languange desk === //
    'h1-deks' => 'PENDAHULUAN',
    'p-desk-1' => ' Kitab Mishkat al-Masabih disusun oleh Waliud-din Abdullah Muhammad bin ‘Abdullah al Khatib al-Umari at-Tibrizi ( w. 741 H) atau lebih dikenali Khatib al-Tibrizi. Kitab ini menambah baik kekurangan yang terdapat dalam kitab Masabih al-Sunnah oleh Imam Al-Baghawi (W. 516 H).',
    'p-desk-2' => 'Kitab ini boleh diibaratkan sebagai <span class="poppins-bold text-[#E67E4D]">ringkasan kepada Sahih Bukhari</span>  di mana penyusunan isi kandungannya hampir sama dengan sahih tersebut. Apa yang membezakan di antara keduanya ialah bilangan hadis yang lebih banyak terdapat di dalam Sahih Bukhari dan juga taraf hadis. Pembaca kitab ini akan dapat menghayati tuntutan hidup seorang muslim berdasarkan sunnah Rasulullah SAW. Selain dari itu, perbahasan dipecahkan kepada beberapa fasal mengikut orientasi isi kandungan hadith memudahkan pembaca membuat rujukan kepada mana-mana hadith yang dikehendaki.',
    'p-deks-3' => "Penulis iaitu Imam Baghawi dan Imam al-Tibrizi ternyata tidak meletakkan hadith-hadith yang dianggap sahih sahaja di dalam kitab mereka. Ini menyebabkan bercampurnya hadith-hadith yang dhaif dan tidak boleh dijadikan hujjah dengan hadith-hadith yang sahih.",
    'p-deks-4' => 'Memandangkan setakat hari ini masih belum terdapat mana-mana aplikasi digital yang memfokuskan kepada rujukan kitab Mishkat al-Masabih dan kesesuaian kitab ini untuk dijadikan sebagai sumber rujukan secara maya, maka pihak Elzar Shariah Solution Sdn Bhd sebagai pengurus projek ingin membangunkan sebuah aplikasi pintar atau apps yang diberi nama <span class="poppins-bold text-[#E67E4D]" >Masabih</span> ini untuk memudahkan masyarakat dan Umat Islam di Malaysia khususnya untuk mendapatkan akses dan maklumat <span class="poppins-bold text-[#E67E4D]">hadis dan fiqh hadis</span> serta jawapan kepada persoalan-persoalan dalam kehidupan berpandukan hadis yang berkaitan secara terus dan pantas.',
    'p-deks-5' => ' Web dan Aplikasi Mobil Masabih diharap dapat mencelikkan masyarakat Islam mengenai kepentingan hadis dan sunnah Nabi Muhammad SAW selain menjadi panduan dan rujukan kepada masyarakat Islam keseluruhannya. Aplikasi ini akan dibangunkan secara sekali gus dan diwakafkan kepada masyarakat awam, ia akan boleh dicapai dan digunakan secara <span class="poppins-bold text-[#E67E4D]">PERCUMA</span>  oleh orang awam.',
];