<?php
return [
   'judul-info' => 'PROJEK AMAL JARIAH ULUNG :',
   'judul-info-2' => 'PENDIGITALAN, TERJEMAHAN & SYARAH KITAB MISHKAT AL-MASABIH',

    // === languange desk === //
    'h1-deks' => 'PENDAHULUAN',
    'p-desk-1' => ' Kitab Mishkat al-Masabih disusun oleh Waliud-din Abdullah Muhammad bin ‘Abdullah al Khatib al-Umari at-Tibrizi ( w. 741 H) atau lebih dikenali Khatib al-Tibrizi. Kitab ini menambah baik kekurangan yang terdapat dalam kitab Masabih al-Sunnah oleh Imam Al-Baghawi (W. 516 H).',
    'p-desk-2' => 'Kitab ini boleh diibaratkan sebagai <span class="poppins-bold text-[#E67E4D]">ringkasan kepada Sahih Bukhari</span>  di mana penyusunan isi kandungannya hampir sama dengan sahih tersebut. Apa yang membezakan di antara keduanya ialah bilangan hadis yang lebih banyak terdapat di dalam Sahih Bukhari dan juga taraf hadis. Pembaca kitab ini akan dapat menghayati tuntutan hidup seorang muslim berdasarkan sunnah Rasulullah SAW. Selain dari itu, perbahasan dipecahkan kepada beberapa fasal mengikut orientasi isi kandungan hadith memudahkan pembaca membuat rujukan kepada mana-mana hadith yang dikehendaki.',
    'p-deks-3' => "Penulis iaitu Imam Baghawi dan Imam al-Tibrizi ternyata tidak meletakkan hadith-hadith yang dianggap sahih sahaja di dalam kitab mereka. Ini menyebabkan bercampurnya hadith-hadith yang dhaif dan tidak boleh dijadikan hujjah dengan hadith-hadith yang sahih.",
    'p-deks-4' => 'Memandangkan setakat hari ini masih belum terdapat mana-mana aplikasi digital yang memfokuskan kepada rujukan kitab Mishkat al-Masabih dan kesesuaian kitab ini untuk dijadikan sebagai sumber rujukan secara maya, maka pihak Elzar Shariah Solution Sdn Bhd sebagai pengurus projek ingin membangunkan sebuah aplikasi pintar atau apps yang diberi nama <span class="poppins-bold text-[#E67E4D]" >Masabih</span> ini untuk memudahkan masyarakat dan Umat Islam di Malaysia khususnya untuk mendapatkan akses dan maklumat <span class="poppins-bold text-[#E67E4D]">hadis dan fiqh hadis</span> serta jawapan kepada persoalan-persoalan dalam kehidupan berpandukan hadis yang berkaitan secara terus dan pantas.',
    'p-deks-5' => ' Web dan Aplikasi Mobil Masabih diharap dapat mencelikkan masyarakat Islam mengenai kepentingan hadis dan sunnah Nabi Muhammad SAW selain menjadi panduan dan rujukan kepada masyarakat Islam keseluruhannya. Aplikasi ini akan dibangunkan secara sekali gus dan diwakafkan kepada masyarakat awam, ia akan boleh dicapai dan digunakan secara <span class="poppins-bold text-[#E67E4D]">PERCUMA</span>  oleh orang awam.',

    // === language MTP === //
    'MTP-JUDUL' => "METODOLOGI PROJEK",
    'MTP-P' => "Projek ini akan menggunakan metod perpustakaan. Kitab yang akan digunakan sebagai bahan rujuk sebagai maklumat utama dalam pembinaan aplikasi Masabih.com ini adalah Midraj ul-Fawatih yang merupakan susunan semula hasil gabungan dua kitab hadis terkemuka dunia yang telah diterjemahkan ke dalam bahasa Melayu iaitu Masabih al-Sunnah dan Mishkat al-Masabih.",
    'MTP-LIST-1' => 'Melantik penterjemah & pensyarah hadis',
    'MTP-LIST-2' => 'Mengenalpasti dan melantik para penyemak ke atas terjemahan dan syarahan hadis',
    'MTP-LIST-3' => 'Melantik para ilmuwan untuk mengenalpasti status kekuatan hadis dan matan hadis iaitu dari sudut Sahih, Hasan atau Dhoif',
    'MTP-LIST-4' => 'Melantik ilmuwan hadis untuk melaksanakan takhrij kepada semua hadis yang dalam kajian.Terjemahan, syarahan serta status dan takhrij lebih 6000 buah hadis ini dijangka akan mengambil masa dalam setahun',


    'paragrap-1' => 'Oleh kerana tempoh pelaksanaan dan pelancaran aplikasi ini mengambil masa yang agak singkat, pihak kami sebagai pengurus projek bagi aplikasi <span class="text-[#E67E4D] poppins-bold">Masabih</span> ini memerlukan dana yang besar untuk memastikan projek ini dapat dilaksanakan dengan jayanya.',
    'paragrap-2' => 'Setakat ini, pihak kami <span class="text-[#E67E4D] poppins-bold"> sudah pun memulakan tugasan dan sekitar 5000 hadis sudah sedia siap </span> diterjemah dan syarah ringkas. Ketika ini, semua syarahan dan terjemahan telah dimasukkan, sementara menunggu hasil semakan lapis kedua dan ketiga. Sejurus semakan lapisan kedua dan ketiga siap, kami akan memasukkan versi siap pinda ke web ini.',

    // === language kos pbr === //
    'p-pbr-language' => 'Kos yang dicadangkan bagi projek ini adalah agak tinggi memandangkan ianya disusun khas oleh syarikat kami secara persendirian serta beberapa orang developer luar dengan anggaran dan target masa untuk menyiapkan projek ini untuk dibuat dalam masa setahun sahaja. Ini memerlukan bilangan developer dan penyemak yang ramai untuk memastikan segala kelancaran serta proses pembikinan web ini dapat berjalan dengan lancar dan cepat. Dianggarkan kos keseluruhan bagi projek ini adalah sebanyak <span class="text-[#E67E4D] poppins-bold">RM 512,000</span> . Namun pada ketika web ini mula boleh dilayari secara atas talian, jumlah derma baru mencecah sekitar RM 73,000 dan kami sudah pun menggunakan wang derma terbabit untuk pembikinan web ini serta membayar pakar hadis dan ilmuan untuk terjamahan dan syarahan walaupun BELUM dana mencukupi. Boleh derma kepada porjek ini di link berikut : <span class="text-[#E67E4D] poppins-bold"><a href="https://myinfaq.org/kempen/projek-amal-jariah-ulung-pendigitalan-terjemahan-syarah-kitab-mishkat-al-masabih/">https://myinfaq.org/kempen/projek-amal-jariah-ulung-pendigitalan-terjemahan-syarah-kitab-mishkat-al-masabih/</a></span> '
];